### 함수 2025.06.11

In [14]:
# 함수: 데이터를 받고, 처리(연산)하고 결과를 반환하는 코드들의 묶음
#       -> 호출을 통해 코드를 실행
# 중복코드를 줄일 수 있다. => 유지보수, 관리가 수월해진다!
# def 함수이름(매개변수, 매개변수, 매개변수, ...)
#   처리작업 코드들..
#   return 값(data: 파이썬에서 제공하는 타입의 모든 데이터)
# ~~ 위 규칙은 변하지 않음!!!!!!!

In [15]:
# 함수정의
# 숫자 두 개를 받아 => 매개변수: 선택사항
# 덧셈연산을 하고   => 내부 처리 작업
# 결과 값을 반환    => 반환 값: 선택사항

def add(n1, n2):        # 함수 정의: 이름, 매개변수
    result = n1 + n2    # 연산, 처리, 작업
    return result       # 결과 값 반환

In [16]:
print(type(add))

<class 'function'>


In [17]:
add(10, 20)     # 호출: 이름과 괄호안에() 매개변수가 받을 수 있는 데아터를 함께 전달

30

In [18]:
add(10,30)

40

In [19]:
def alert_msg():
    return '안녕하세요. 회원님 감사합니다.'

In [20]:
print(alert_msg())

안녕하세요. 회원님 감사합니다.


In [21]:
# 매개변수는 있고, 반환값이 없는 함수
# 숫자 두개를 받아 덧셈연산의 결과를 출력하는 함수

def add_print(n1, n2):
    result = n1 + n2
    print(f'{n1}+{n2}={n1+n2}')

In [22]:
add_print(1,2)

1+2=3


In [23]:
result_add_print = add_print(10, 200)

10+200=210


In [24]:
print(result_add_print)

None


In [25]:
# 매개변수도 없고, 반환도 없는 함수

def display_menu():
    menu = '''
1. 아메리카노
2. 라떼
3. 에스프레소
'''
    print(menu)

In [26]:
display_menu()


1. 아메리카노
2. 라떼
3. 에스프레소



In [27]:
def sub(n1, n2):
    return n1 - n2

In [28]:
sub(n2 = 3, n1 = 10)

7

In [29]:
# 매개변수를 지정하고 값을 넣어줌
print('KING', 'hello', sep='\t', end='\t')
print('KING', 'hello', sep=',')

KING	hello	KING,hello


In [30]:
# 매개변수가 여러개인데 몇개인지 몰라 ?!

print('king')
print(1,2,3,4,5)

king
1 2 3 4 5


In [31]:
# 매개변수에서 전달되는 숫자들(몇개?)을
# 모두 더한 값을 
# 반환하는 함수

def add_sum(*args):
    print(type(args))
    print(args)
    sum = 0
    for num in args:
        sum += num
    return sum

In [32]:
add_sum(1,2,3,4,5,6,7,8,9)

<class 'tuple'>
(1, 2, 3, 4, 5, 6, 7, 8, 9)


45

In [33]:
# 연산의 타입을 전달 받고 전달되는 숫자들의 
# 연산한 결과를 
# 반환하는 함수

def add_type(type, *args):
    if type == 'add':
        result = 0
        for num in args:
            result += num
        return result
    elif type == 'mul':
        result = 1
        for num in args:
            result *= num
        return result
    else:
        print('사용가능한 타입을 선택해주세요!')

In [34]:
print(add_type('add', 1,2,3,4,5,6,7))
print(add_type('mul', 1,2,3,4,5,6,7))

28
5040


In [35]:
def print_args(**args):
    print(args)
    print(type(args))

In [36]:
print_args(name='손흥민', age = 20)

{'name': '손흥민', 'age': 20}
<class 'dict'>


In [37]:
player1 = {
    'name' : '손흥민',
    'age' : 20
}

In [38]:
player2 = print_args(name = '손흥민', age = 30)

{'name': '손흥민', 'age': 30}
<class 'dict'>


In [39]:
print(player1)
print(player2)

{'name': '손흥민', 'age': 20}
None


In [40]:
def add_mul_return(n1, n2):
    add_result = n1 + n2
    mul_result = n1 * n2
    return(add_result, mul_result)

In [41]:
add_mul_return(10, 20)

(30, 200)

In [42]:
result1, result2 = add_mul_return(10, 20)
print(result1, result2)

30 200


In [43]:
# 매개변수의 

In [44]:
# 이름, 나, 성별 받아서 출력 함수
def say_hi(name, age, gender = True): # Gender=True => 여성
    print(f'안녕하세요. 저는 {name} 입니다. 나이는 {age} 입니다.')
    if gender:
        print('여성입니다.')
    else:
        print('남성입니다.')


In [45]:
say_hi('손흥민', 30, False)

안녕하세요. 저는 손흥민 입니다. 나이는 30 입니다.
남성입니다.


In [46]:
# 변수의 사용 범위

a = 1

def var_test(a):    # 지역변수가 우선!
    print('함수 내부의 a:', a)

In [47]:
var_test(10)

함수 내부의 a: 10


In [48]:
print(a)

1


In [ ]:
# 같은 이름이면 외부 a로 실행됨 
def var_test2():
    global a    # 전역변수를 사용할 때, 사용은 지양함
    a = a + 1
    print(a)

In [50]:
var_test2()

2


In [51]:
print(a)

2


In [52]:
# lambda 함수 => 한줄로 간단하게 표현하는 함수 표현식
# 함수이름 = lambda arg1, arg2 ... : 연산
# 숫자 두개를 전달받아 덧셈한 결과를 반환하는 함수

add3 = lambda n1, n2 : n1+n2
add3(100,10)

110

In [53]:
# 내장함수: 파이썬 설치 -> 기본으로 제공하는 함수

st_names = ['king', 'cool', 'hot', 'scott']

In [54]:
# 학생들의 index 값을 함께 출력

num = 0

for name in st_names:
    print(num, name)
    num += 1

0 king
1 cool
2 hot
3 scott


In [55]:
for index, name in enumerate(st_names, start=1):
    print(index, name)

1 king
2 cool
3 hot
4 scott


In [56]:
# filter: 필터링(매개변수로 전달되는 함수: 요소 값을 판단해서 논리값 반환)을 통해 새로운 리스트를 생성 반환
# filter(fn, itr)
def positive(l):
    result = []
    for n in l:
        if n > 0:
            result.append(n)
    return result

In [57]:
print(positive([3,1,-1,-3,0,9,10,4]))

[3, 1, 9, 10, 4]


In [58]:
# filter
# 판별함수
def positive_fn(x):
    return x > 0

In [59]:
list(filter(positive_fn, [3,1,-1,-3,0,9,10,4]))

[3, 1, 9, 10, 4]

In [60]:
# 홀수만 출력
def pos_fn2(x):
    return x % 2 == 1

In [61]:
list(filter(pos_fn2, [3,1,-1,-3,0,9,10,4]))

[3, 1, -1, -3, 9]

In [62]:
list(filter(lambda x : x > 0, [3,1,-1,-3,0,9,10,4]))

[3, 1, 9, 10, 4]

In [63]:
# map이 새로운 값을 만듬
list(map(lambda x: x*2, [1,2,3,4,5]))

[2, 4, 6, 8, 10]

In [64]:
# 파이썬의 입출력(자원)
# 표준 입출력 => input, print
# 텍스트 파일(자원): 입출력 I/O
# 파일 단위 입출력: Open(자원의 경로, 모드) 모드 => r(read), w(write), a(append)

f = open('new_text.txt', 'w')
f.close()

In [65]:
f = open('new_text.txt', 'w')   # 1. 파일 오픈: w
f.write('안녕하세요!')             # 2. 텍스트 쓰기
f.close()

In [66]:
f = open('new_text.txt', 'w')  
for i in range(1, 11):
    f.write(f'{i}번째 줄 입력\n')
f.close()

In [67]:
# 파일 내용 읽어오기
f = open('new_text.txt', 'r')
line1 = f.readline()
print(line1)
line2 = f.readline()
print(line2)
f.close()

1번째 줄 입력

2번째 줄 입력



In [ ]:
# 파일 내용 읽어오기
f = open('new_text.txt', 'r')

while 1:
    line =# f.readline()
    if not line:
        break
    print(line, end='')
f.close()

1번째 줄 입력
2번째 줄 입력
3번째 줄 입력
4번째 줄 입력
5번째 줄 입력
6번째 줄 입력
7번째 줄 입력
8번째 줄 입력
9번째 줄 입력
10번째 줄 입력


In [69]:
f = open('new_text.txt', 'r')
lines = f.readlines()
print(lines)
for line in lines:
    print(line, end = '')
f.close()

['1번째 줄 입력\n', '2번째 줄 입력\n', '3번째 줄 입력\n', '4번째 줄 입력\n', '5번째 줄 입력\n', '6번째 줄 입력\n', '7번째 줄 입력\n', '8번째 줄 입력\n', '9번째 줄 입력\n', '10번째 줄 입력\n']
1번째 줄 입력
2번째 줄 입력
3번째 줄 입력
4번째 줄 입력
5번째 줄 입력
6번째 줄 입력
7번째 줄 입력
8번째 줄 입력
9번째 줄 입력
10번째 줄 입력


In [70]:
# append: 데이터 추가
f = open('new_text.txt', 'a')
f.write(f'새로운 행이 추가 됩니다.\n')
f.close()

In [71]:
# append: 데이터 추가
f = open('new_text.txt', 'a')
for i in range(16, 21):
    f.write(f'새로운 행이 {i}가 추가 됩니다.\n')
f.close()

In [72]:
# close 생략 가능한 구현 => with
with open('new_text.txt', 'r') as file:
    lines = file.readlines()
    print(lines)

['1번째 줄 입력\n', '2번째 줄 입력\n', '3번째 줄 입력\n', '4번째 줄 입력\n', '5번째 줄 입력\n', '6번째 줄 입력\n', '7번째 줄 입력\n', '8번째 줄 입력\n', '9번째 줄 입력\n', '10번째 줄 입력\n', '새로운 행이 추가 됩니다.\n', '새로운 행이 16가 추가 됩니다.\n', '새로운 행이 17가 추가 됩니다.\n', '새로운 행이 18가 추가 됩니다.\n', '새로운 행이 19가 추가 됩니다.\n', '새로운 행이 20가 추가 됩니다.\n']


In [73]:
# 예외처리: 에러 발생 시에 비정상적인 종료를 막기 위한 처리

try:
    print(10/5)
except:
    print('에러가 발생했습니다. 에러에 대한 처리를 합니다.')

print('프로그램을 종료합니다.')


2.0
프로그램을 종료합니다.


In [74]:
list_t = [1,2,3,4,5]

In [75]:
try:
    print(10/2)
    print(list_t[10])   # <=====
except ZeroDivisionError:
    print('0으로 나누는 연산은 불가능합니다.')
except NameError:
    print('정의되지 않은 식별자 입니다.')
except IndexError:
    print('리스트의 index 범위에서 벗어납니다.')
except:
    print('에러발생!!!')

5.0
리스트의 index 범위에서 벗어납니다.


In [76]:
try :
    print(10/2)
    print(list_t[1]) # <=======
    print(uname)
except ZeroDivisionError as e :
    print('0으로 나누는 연산을 불가능합니다.')
    print(e)
except (NameError, IndexError) as e:
    #print('정의되지 않은 식별자 입니다.')
    print('에러가 발생했습니다.')
    print(e)
# except IndexError as e:
#     print('리스트의 index 범위에서 벗어납니다')
#     print(e)
except :
    print('에러발생!!!')

5.0
2
에러가 발생했습니다.
name 'uname' is not defined


In [77]:
# try: except: finally: -> 에러 발생여부와 상관없이 실행되어야 하는 블록
try:
    print('hello')
    print(10/0)
except:
    print('error!!')
finally:
    print('!!!!!')

hello
error!!
!!!!!


In [78]:
try:
    age = int(input('나이를 입력하세요.'))
except:
    print('숫자 형식으로 입력해주세요!')
else:
    if age > 18:
        print('입장')
    else:
        print('불가')
        

입장


In [79]:
# 사용자 정의 예외 타입 정의
# 논리적인 오류 발생 -> 예외로 처리
# age => 음수, 500: 논리적 오류

class MyError(Exception):
    pass

In [80]:
# 에러 강제 발생
# raise MyError()

In [81]:
try:
    age = int(input('나이를 입력하세요.'))
    
    if age < 1 or age > 200:
        raise MyError()
    
except MyError:
    print('나이의 입력 범위는 1 ~ 200 까지 입니다.\n다시 입력하세요!')
except:
    print('다시 입력하세요!')
else:
    print(age)

34


### 클래스 2025.06.12

In [ ]:
# 객체지향 프로그래밍: 객체의 개념을 프로그래밍에 도입
# 객체: 변수들, 함수들도 구성 => 메모리에 올라가 있는 상태
# 클래스: 변수들과 함수들이 어떻게 구성되는지의 설계도 -> 변수들을 정의, 함수들을 정의
#   => 클래스만 정의했다. -> 사용 X, 클래스를 이용해서 객체로 만들어야 사용가능
# class 클래스이름:
#       변수들과 함수들을 정의
# 클래스의 정의 => 새로운 사용자 정의 타입을 만든 것!
# 객체 생성 => 변수 = 클래스이름()
# 객체의 활용 => 변수.객체가 가지는 변수, 변수.객체가 가지는 함수() 메서드(객체가 가지는 함수)

class Cookie:
    pass

In [85]:
# 객체 생성
c1 = Cookie()
c2 = Cookie()

print(id(c1), type(c1))
print(id(c2), type(c2))

4362940368 <class '__main__.Cookie'>
4362943248 <class '__main__.Cookie'>


In [134]:
# 사칙연산을 하는 클래스 정의: 클래스 이름, 변수, 함수
# 변수는 두개, 함수(메서드) 4개

class FourCal:
    # 초기화(변수 선언 -> 최초 데이터를 할당) 메서드 => 생성자, 생성자함수
    # 필요한 변수들의 생성, 값을 초기화
    def __init__(self, first, second):
        self.first = first
        self.second = second

    # 클래스에서 함수를 정의할 때에는 반드시 self 매개변수를 받아야 한다!
    # self => 객체 자신을 가르키는 변수(객체의 주소)
    def setdata(self, first, second):
        self.first = first
        self.second = second

    # 사칙연산 함수
    def add(self):
        return self.first + self.second
    
    def sub(self):
        return self.first - self.second
    
    def mul(self):
        return self.first * self.second
    
    def div(self):
        return self.first / self.second


In [88]:
cal_1 = FourCal()

In [89]:
type(cal_1)

__main__.FourCal

In [90]:
cal_1.setdata(10, 20)

In [93]:
print(cal_1.first, cal_1.second)

10 20


In [94]:
cal_2 = FourCal()

In [98]:
cal_3 = FourCal()

In [103]:
cal_4 = FourCal(100,200)
cal_4.first

100

In [105]:
cal_5 = FourCal(10, 7)

In [110]:
print(cal_5.first, cal_5.second)
print(cal_5.add())
print(cal_5.sub())
print(cal_5.mul())
print(cal_5.div())

10 7
17
3
70
1.4285714285714286


In [ ]:
# 학생 class 생성 -> 객체 생성
# 변수: 학번, 이름, 국어점수, 영어점수, 수학점수
# 기능: 전체 데이터 출력하는 메서드(이름, 학번, 총점, 평균)
#       총점 계산
#       평균 계산
# 시뮬레이션: 테스트 학생 데이터 생성 -> 결과 출력

class Student:
    # 데이터 초기화
    def __init__(self, student_id, name, kor, eng, math):
        self.id = student_id
        self.name = name
        self.kor = kor
        self.eng = eng
        self.math = math


    def total(self):
        return self.kor + self.eng + self.math
    
    def average(self):
        return self.total() / 3
    
    def print_info(self):
        print(f'이름: {self.name}')
        print(f'학번: {self.id}')
        print(f'총점: {self.total()}')
        print(f'평균: {self.average():.2f}')
        print('-'*20)

In [125]:
student_1 = Student('20250612','이순신',90,80,60)
student_2 = Student('20250613','손흥민',60,75,30)

In [127]:
student_1.print_info()
student_2.print_info()

이름: 이순신
학번: 20250612
총점: 230
평균: 76.67
--------------------
이름: 손흥민
학번: 20250613
총점: 165
평균: 55.00
--------------------


In [ ]:
# students = [
#     Student('20250612','이순신',90,80,60)
#     Student('20250612','이순신',90,80,60)
#     Student('20250612','이순신',90,80,60)
#     Student('20250612','이순신',90,80,60)
# ]

In [142]:
# 클래스의 상속: 세로운 클래스를 만들 때 기존의 클래스의 멤버들을 받아서 생성하는 방법
# class 클래스이름(부모클래스)
class MoreFourCal(FourCal):
    def pow(self):
        return self.first ** self.second
    
    def div(self):
        if self.second == 0:
            return 0
        else:
            return self.first / self.second

In [143]:
mcal_1 = MoreFourCal(100,2)

In [144]:
print(mcal_1.add())
print(mcal_1.sub())
print(mcal_1.mul())
print(mcal_1.div())



102
98
200
50.0


In [145]:
mcal_2 = MoreFourCal(100,0)

In [147]:
print(mcal_2.add())
print(mcal_2.mul())
print(mcal_2.div())
print(mcal_2.pow())


100
0
0
1


#### 표준모듈

In [149]:
import datetime

In [160]:
day1 = datetime.date(2025, 6, 12)
day2 = datetime.date(2025, 1, 1)

In [161]:
print(day1 - day2)

162 days, 0:00:00


In [162]:
import time

In [163]:
time.time()

1749711462.693459

In [167]:
time.localtime()

time.struct_time(tm_year=2025, tm_mon=6, tm_mday=12, tm_hour=15, tm_min=58, tm_sec=21, tm_wday=3, tm_yday=163, tm_isdst=0)

In [168]:
time.ctime()

'Thu Jun 12 15:58:35 2025'

#### 랜덤

In [169]:
import random

In [171]:
random.random()     # 1보다 작은 값 / 0.00000 <= R < 1

0.9332506299920373

In [172]:
random.randint(60,100)

86

In [173]:
list_score = []
for s in range(0, 10):
    list_score.append(random.randint(60, 100))

print(list_score)

[77, 74, 88, 84, 99, 65, 97, 78, 76, 79]


In [174]:
random.choice([1,2,3,4,5,5,6,7,8])

8

In [175]:
random.sample([1,2,3,4,5,6,7,8,9], 5)

[6, 1, 7, 9, 4]

#### OS

In [176]:
import os

In [177]:
os.chdir('/Users/minjung')

In [178]:
os.getcwd()

'/Users/minjung'

In [181]:
os.chdir('/Users/minjung/sk-ai/py_project')

In [ ]:
# 디렉토리 생성
os.mkdir('test')

In [ ]:
# 디렉토리 삭제
os.rmdir('test')

In [184]:
import json

In [185]:
with open('data.json', 'r', encoding='utf8') as f:
    data = json.load(f)

In [186]:
print(data, type(data))

{'name': '손흥민', 'age': 30, 'number': 7} <class 'dict'>


In [187]:
json_str_data = json.dumps(data)

In [188]:
print(json_str_data, type(json_str_data))

{"name": "\uc190\ud765\ubbfc", "age": 30, "number": 7} <class 'str'>


In [192]:
import numpy as np

In [193]:
arr = np.array([1,2,3,4,5])

In [194]:
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [195]:
arr + 10

array([11, 12, 13, 14, 15])

In [196]:
# 1로 채우는 배열
ones = np.ones((3,2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [199]:
# 일련번호 생성되는 배열
# 0 ~ 10 사이의 숫자를 2씩 간격으로 생성
seq_1 = np.arange(0, 10, 2)
print(seq_1)

[0 2 4 6 8]


In [ ]:
# 지정된 범위 안에서 동일한 간격으로 숫자를 생성
# 0 ~ 10 5개로 구분
linspace = np.linspace(1, 10, 4)
print(linspace)

[ 1.  4.  7. 10.]


In [201]:
# 배열의 속성 확인
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [203]:
print(type(arr1))
print(arr1.shape)
print(arr1.ndim)
print(arr1.size)
print(arr1.dtype)

<class 'numpy.ndarray'>
(3, 3)
2
9
int64
