### 클래스 2025.06.12

In [30]:
# 객체지향 프로그래밍: 객체의 개념을 프로그래밍에 도입
# 객체: 변수들, 함수들도 구성 => 메모리에 올라가 있는 상태
# 클래스: 변수들과 함수들이 어떻게 구성되는지의 설계도 -> 변수들을 정의, 함수들을 정의
#   => 클래스만 정의했다. -> 사용 X, 클래스를 이용해서 객체로 만들어야 사용가능
# class 클래스이름:
#       변수들과 함수들을 정의
# 클래스의 정의 => 새로운 사용자 정의 타입을 만든 것!
# 객체 생성 => 변수 = 클래스이름()
# 객체의 활용 => 변수.객체가 가지는 변수, 변수.객체가 가지는 함수() 메서드(객체가 가지는 함수)

class Cookie:
    pass

In [31]:
# 객체 생성
c1 = Cookie()
c2 = Cookie()

print(id(c1), type(c1))
print(id(c2), type(c2))

4428440512 <class '__main__.Cookie'>
4424972432 <class '__main__.Cookie'>


In [32]:
# 사칙연산을 하는 클래스 정의: 클래스 이름, 변수, 함수
# 변수는 두개, 함수(메서드) 4개

class FourCal:
    # 초기화(변수 선언 -> 최초 데이터를 할당) 메서드 => 생성자, 생성자함수
    # 필요한 변수들의 생성, 값을 초기화
    def __init__(self, first, second):
        self.first = first
        self.second = second

    # 클래스에서 함수를 정의할 때에는 반드시 self 매개변수를 받아야 한다!
    # self => 객체 자신을 가르키는 변수(객체의 주소)
    def setdata(self, first, second):
        self.first = first
        self.second = second

    # 사칙연산 함수
    def add(self):
        return self.first + self.second
    
    def sub(self):
        return self.first - self.second
    
    def mul(self):
        return self.first * self.second
    
    def div(self):
        return self.first / self.second


In [33]:
cal_1 = FourCal(1, 2)

In [34]:
type(cal_1)

__main__.FourCal

In [35]:
cal_1.setdata(10, 20)

In [36]:
print(cal_1.first, cal_1.second)

10 20


In [37]:
cal_2 = FourCal(1,2)

In [38]:
cal_3 = FourCal(2,3)

In [39]:
cal_4 = FourCal(100,200)
cal_4.first

100

In [40]:
cal_5 = FourCal(10, 7)

In [41]:
print(cal_5.first, cal_5.second)
print(cal_5.add())
print(cal_5.sub())
print(cal_5.mul())
print(cal_5.div())

10 7
17
3
70
1.4285714285714286


In [42]:
# 학생 class 생성 -> 객체 생성
# 변수: 학번, 이름, 국어점수, 영어점수, 수학점수
# 기능: 전체 데이터 출력하는 메서드(이름, 학번, 총점, 평균)
#       총점 계산
#       평균 계산
# 시뮬레이션: 테스트 학생 데이터 생성 -> 결과 출력

class Student:
    # 데이터 초기화
    def __init__(self, student_id, name, kor, eng, math):
        self.id = student_id
        self.name = name
        self.kor = kor
        self.eng = eng
        self.math = math


    def total(self):
        return self.kor + self.eng + self.math
    
    def average(self):
        return self.total() / 3
    
    def print_info(self):
        print(f'이름: {self.name}')
        print(f'학번: {self.id}')
        print(f'총점: {self.total()}')
        print(f'평균: {self.average():.2f}')
        print('-'*20)

In [43]:
student_1 = Student('20250612','이순신',90,80,60)
student_2 = Student('20250613','손흥민',60,75,30)

In [44]:
student_1.print_info()
student_2.print_info()

이름: 이순신
학번: 20250612
총점: 230
평균: 76.67
--------------------
이름: 손흥민
학번: 20250613
총점: 165
평균: 55.00
--------------------


In [45]:
students = [
    Student('손흥민1', 123451, 80, 70, 50),
    Student('손흥민2', 123452, 80, 70, 50),
    Student('손흥민3', 123453, 80, 70, 50),
    Student('손흥민4', 123454, 80, 70, 50),
    Student('손흥민5', 123455, 80, 70, 50),
]

In [46]:
for s in students:
    s.print_info()

이름: 123451
학번: 손흥민1
총점: 200
평균: 66.67
--------------------
이름: 123452
학번: 손흥민2
총점: 200
평균: 66.67
--------------------
이름: 123453
학번: 손흥민3
총점: 200
평균: 66.67
--------------------
이름: 123454
학번: 손흥민4
총점: 200
평균: 66.67
--------------------
이름: 123455
학번: 손흥민5
총점: 200
평균: 66.67
--------------------


In [47]:
# 클래스의 상속: 세로운 클래스를 만들 때 기존의 클래스의 멤버들을 받아서 생성하는 방법
# class 클래스이름(부모클래스)
class MoreFourCal(FourCal):
    def pow(self):
        return self.first ** self.second
    
    def div(self):
        if self.second == 0:
            return 0
        else:
            return self.first / self.second

In [48]:
mcal_1 = MoreFourCal(100,2)

In [49]:
print(mcal_1.add())
print(mcal_1.sub())
print(mcal_1.mul())
print(mcal_1.div())



102
98
200
50.0


In [50]:
mcal_2 = MoreFourCal(100,0)

In [51]:
print(mcal_2.add())
print(mcal_2.mul())
print(mcal_2.div())
print(mcal_2.pow())


100
0
0
1


#### 표준모듈

In [52]:
import datetime

In [53]:
day1 = datetime.date(2025, 6, 12)
day2 = datetime.date(2025, 1, 1)

In [54]:
print(day1 - day2)

162 days, 0:00:00


In [55]:
import time

In [56]:
time.time()

1749775961.741444

In [57]:
time.localtime()

time.struct_time(tm_year=2025, tm_mon=6, tm_mday=13, tm_hour=9, tm_min=52, tm_sec=41, tm_wday=4, tm_yday=164, tm_isdst=0)

In [58]:
time.ctime()

'Fri Jun 13 09:52:41 2025'

#### 랜덤

In [59]:
import random

In [60]:
random.random()     # 1보다 작은 값 / 0.00000 <= R < 1

0.6337357440052415

In [61]:
random.randint(60,100)

71

In [62]:
list_score = []
for s in range(0, 10):
    list_score.append(random.randint(60, 100))

print(list_score)

[100, 91, 86, 64, 64, 86, 82, 65, 81, 71]


In [63]:
random.choice([1,2,3,4,5,5,6,7,8])

7

In [64]:
random.sample([1,2,3,4,5,6,7,8,9], 5)

[9, 3, 2, 1, 8]

#### OS

In [65]:
import os

In [66]:
os.environ

environ{'COMMAND_MODE': 'unix2003',
        'CONDA_DEFAULT_ENV': 'base',
        'CONDA_EXE': '/opt/anaconda3/bin/conda',
        'CONDA_PREFIX': '/opt/anaconda3',
        'CONDA_PROMPT_MODIFIER': '(base) ',
        'CONDA_PYTHON_EXE': '/opt/anaconda3/bin/python',
        'CONDA_SHLVL': '1',
        'GSETTINGS_SCHEMA_DIR': '/opt/anaconda3/share/glib-2.0/schemas',
        'HOME': '/Users/minjung',
        'HOMEBREW_CELLAR': '/opt/homebrew/Cellar',
        'HOMEBREW_PREFIX': '/opt/homebrew',
        'HOMEBREW_REPOSITORY': '/opt/homebrew',
        'INFOPATH': '/opt/homebrew/share/info:',
        'LOGNAME': 'minjung',
        'MallocNanoZone': '0',
        'OLDPWD': '/',
        'ORIGINAL_XDG_CURRENT_DESKTOP': 'undefined',
        'PATH': '/Users/minjung/sk-ai/py_project/.venv/bin:/opt/anaconda3/bin:/opt/anaconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.13/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.12/bin:/Library/Frameworks/Py

In [67]:
os.chdir('/Users/minjung')

In [68]:
os.getcwd()

'/Users/minjung'

In [69]:
os.chdir('/Users/minjung/sk-ai/py_project')

In [70]:
# 디렉토리 생성
os.mkdir('test')

In [71]:
# 디렉토리 삭제
os.rmdir('test')

In [72]:
import json

In [73]:
with open('data.json', 'r', encoding='utf8') as f:
    data = json.load(f)

In [74]:
print(data, type(data))

{'name': '손흥민', 'age': 30, 'number': 7} <class 'dict'>


In [75]:
json_str_data = json.dumps(data)

In [76]:
print(json_str_data, type(json_str_data))

{"name": "\uc190\ud765\ubbfc", "age": 30, "number": 7} <class 'str'>


In [77]:
import numpy as np

In [78]:
arr = np.array([1,2,3,4,5])

In [79]:
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [80]:
arr + 10

array([11, 12, 13, 14, 15])

In [81]:
# 배열의 생성
# 0으로 채워지는 배열 생성
zeros = np.zeros((1,3))
print(zeros)

[[0. 0. 0.]]


In [82]:
# 1로 채우는 배열
ones = np.ones((3,2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [83]:
# 일련번호 생성되는 배열
# 0 ~ 10 사이의 숫자를 2씩 간격으로 생성
seq_1 = np.arange(0, 10, 2)
print(seq_1)

[0 2 4 6 8]


In [84]:
# 지정된 범위 안에서 동일한 간격으로 숫자를 생성
# 0 ~ 10 5개로 구분
linspace = np.linspace(1, 10, 4)
print(linspace)

[ 1.  4.  7. 10.]


In [85]:
# 배열의 속성 확인
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [87]:
print(type(arr1))
print(arr1.shape)
print(arr1.ndim)
print(arr1.size)
print(arr1.dtype)

<class 'numpy.ndarray'>
(3, 3)
2
9
int64
